# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tune_pb2 as tune_dot_tune__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tune/tune_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TuneServiceStub(object):
    """Enable creating and sending a tune to be played on the system.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayTune = channel.unary_unary(
                '/mavsdk.rpc.tune.TuneService/PlayTune',
                request_serializer=tune_dot_tune__pb2.PlayTuneRequest.SerializeToString,
                response_deserializer=tune_dot_tune__pb2.PlayTuneResponse.FromString,
                _registered_method=True)


class TuneServiceServicer(object):
    """Enable creating and sending a tune to be played on the system.
    """

    def PlayTune(self, request, context):
        """Send a tune to be played by the system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TuneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayTune': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayTune,
                    request_deserializer=tune_dot_tune__pb2.PlayTuneRequest.FromString,
                    response_serializer=tune_dot_tune__pb2.PlayTuneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mavsdk.rpc.tune.TuneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mavsdk.rpc.tune.TuneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TuneService(object):
    """Enable creating and sending a tune to be played on the system.
    """

    @staticmethod
    def PlayTune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mavsdk.rpc.tune.TuneService/PlayTune',
            tune_dot_tune__pb2.PlayTuneRequest.SerializeToString,
            tune_dot_tune__pb2.PlayTuneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
